version: '3'
services:
  web:
    build: .
    volumes:
      - .:/opt/killrvideo-web
    ports:
      - "3000:3000"
    depends_on:
      - dse
      - backend
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug

  backend:
    image: killrvideo/killrvideo-nodejs:3.0.0
    depends_on:
      - dse
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug

  dse:
    image: datastax/dse-server:6.7.0
    command: [ -s -g ]
    ports:
      - "9042:9042"
      - "8983:8983"
      - "8182:8182"
    environment:
      DS_LICENSE: accept
    # Allow DSE to lock memory with mlock
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1

  dse-config:
    image: killrvideo/killrvideo-dse-config:3.0.0
    environment:
      KILLRVIDEO_SERVICE_DISCOVERY_DISABLED: 'true'
    depends_on:
      - dse

  generator:
    image: killrvideo/killrvideo-generator:3.0.0
    depends_on:
      - dse
      - backend
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug
