import {ADD_COMMENT,ADD_COMMENT_RESET,ADD_ANOTHER_COMMENT,GET_VIDEO,RECORD_PLAYBACK,RESET_VIDEO,UPDATE_VIDEO_LOCATION,RATE_VIDEO,UPLOAD_VIDEO,UPLOAD_VIDEO_PROGRESS,ADD_UPLOADED_VIDEO,CLEAR_UPLOAD_VIDEO_SELECTION,SET_SOURCE,VALIDATE_YOUTUBE_URL,SET_YOUTUBE_VIDEO,ADD_YOUTUBE_VIDEO,CLEAR_YOUTUBE_VIDEO,GET_SUGGESTIONS,CLEAR_SUGGESTIONS,MONITOR,CHANGED,UNLOAD
} from "../consts"


export function addComment(videoId, comment) {

}

export function recentVideos() {

}

export function recommendedVideos() {

}

export function myVideos() {

}

