# Allow configuration in YAML files to be overridden by environment variable values
loggingLevel: KILLRVIDEO_LOGGING_LEVEL

client:
  youTubeApiKey: KILLRVIDEO_YOUTUBE_API_KEY

web:
  session:
    secret: KILLRVIDEO_SESSION_SECRET

cassandra:
  replication: KILLRVIDEO_CASSANDRA_REPLICATION
  dseUsername: KILLRVIDEO_DSE_USERNAME
  dsePassword: KILLRVIDEO_DSE_PASSWORD

services:
  cassandra: KILLRVIDEO_DSE_CONTACT_POINTS
