//User Reducer
export const GET_USER="GET_USER";
export const RESET_USER="RESET_USER";
export const LOGIN="LOGIN";
export const LOGOUT="LOGOUT";
export const GET_CURRENT_USER="GET_CURRENT_USER";
export const REGISTER="REGISTER";

//Chat Reducer
export const JOIN_ROOM="JOIN_ROOM";
export const LEAVE_ROOM="LEAVE_ROOM";
export const GET_MESSAGES="GET_MESSAGES";
export const SEND_MESSAGE="SEND_MESSAGE";
export const USER_JOINED="USER_JOINED";
export const USER_LEFT="USER_LEFT";
export const NEW_MESSAGE="NEW_MESSAGE";

//Video Reducer
export const ADD_COMMENT="ADD_COMMENT";
export const ADD_COMMENT_RESET="ADD_COMMENT_RESET";
export const ADD_ANOTHER_COMMENT="ADD_ANOTHER_COMMENT";
export const GET_VIDEO="GET_VIDEO";
export const RECORD_PLAYBACK="RECORD_PLAYBACK";
export const RESET_VIDEO="RESET_VIDEO";
export const UPDATE_VIDEO_LOCATION="UPDATE_VIDEO_LOCATION";
export const RATE_VIDEO="RATE_VIDEO";
export const UPLOAD_VIDEO="UPLOAD_VIDEO";
export const UPLOAD_VIDEO_PROGRESS="UPLOAD_VIDEO_PROGRESS";
export const ADD_UPLOADED_VIDEO="ADD_UPLOADED_VIDEO";
export const CLEAR_UPLOAD_VIDEO_SELECTION="CLEAR_UPLOAD_VIDEO_SELECTION";
export const SET_SOURCE="SET_SOURCE";
export const VALIDATE_YOUTUBE_URL="VALIDATE_YOUTUBE_URL";
export const SET_YOUTUBE_VIDEO="SET_YOUTUBE_VIDEO";
export const ADD_YOUTUBE_VIDEO="ADD_YOUTUBE_VIDEO";
export const CLEAR_YOUTUBE_VIDEO="CLEAR_YOUTUBE_VIDEO";
export const GET_SUGGESTIONS="GET_SUGGESTIONS";
export const CLEAR_SUGGESTIONS="CLEAR_SUGGESTIONS";
export const MONITOR="MONITOR";
export const CHANGED="CHANGED";
export const UNLOAD="UNLOAD";

//Misc Reducer
export const SET_CONFIG="SET_CONFIG";
export const TOGGLE_WHAT_IS_THIS="TOGGLE_WHAT_IS_THIS";
export const SHOW_TOUR="SHOW_TOUR";

//Nav Reducer
export const CHANGE_SCREEN="CHANGE_SCREEN";